spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306
    username: root
    password: 556234
  docker:
    compose:
#      TODO : start only for production
      lifecycle-management: start_and_stop


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG

server:
    port: 9231
    ssl:
#     TODO : change to production keystore
      certificate: "classpath:keystore/my-cert.pem"
      certificate-private-key: "classpath:keystore/my-cert-key.pem"
      trust-certificate: "classpath:keystore/ca-cert.pem"